'use strict';
const card=document.querySelector('#card'),front=document.querySelector('#front'),back=document.querySelector('#back'),side=document.querySelector('#side');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
const MAX_TILT=45,SWIPE_DISTANCE=68;
let flat=reduced.matches,activeBack=false,angle=0,base=0,animation=0,busy=false,gesture=null,suppressClick=false;
function a11y(b){const changed=activeBack!==b;activeBack=b;card.dataset.side=b?'back':'front';front.inert=b;back.inert=!b;front.setAttribute('aria-hidden',String(b));back.setAttribute('aria-hidden',String(!b));if(changed)side.textContent=b?'Verso do cartão':'Frente do cartão';}
function render(){card.style.transform=`rotateY(${angle}deg)`;card.style.setProperty('--light-x',`${50+Math.sin(angle*Math.PI/180)*45}%`);card.style.setProperty('--light-y','50%');card.style.setProperty('--shine',gesture?.horizontal||busy?'.32':'.045');card.style.setProperty('--foil-offset',`${Math.sin(angle*Math.PI/180)*48}%`);card.style.setProperty('--shadow-x',`${Math.sin(angle*Math.PI/180)*-12}px`);if(!flat)a11y(Math.cos(angle*Math.PI/180)<0);}
function stop(){cancelAnimationFrame(animation);animation=0;busy=false;}
function animate(target,duration=430,complete=()=>{}){stop();if(flat){angle=target;render();complete();return;}busy=true;const start=angle,time=performance.now();function tick(now){const p=Math.min(1,(now-time)/duration),e=p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;angle=start+(target-start)*e;render();if(p<1)animation=requestAnimationFrame(tick);else{animation=0;busy=false;complete();render();}}animation=requestAnimationFrame(tick);}
function flip(direction=1){if(busy)return;if(gesture)gesture.consumed=true;const destination=!activeBack;if(flat){base=destination?180:0;angle=base;a11y(destination);render();return;}const target=base+(direction<0?-180:180);animate(target,560,()=>{base=destination?180:0;angle=base;a11y(destination);});}
function clearGesture(){if(gesture&&card.hasPointerCapture(gesture.id))card.releasePointerCapture(gesture.id);gesture=null;card.classList.remove('dragging');}
function reset(){stop();clearGesture();base=0;angle=0;a11y(false);render();}
card.addEventListener('pointerdown',e=>{if(flat||busy||gesture||e.isPrimary===false||e.button>0)return;suppressClick=false;gesture={id:e.pointerId,startX:e.clientX,startY:e.clientY,horizontal:false,consumed:false};});
window.addEventListener('pointermove',e=>{if(!gesture||e.pointerId!==gesture.id||gesture.consumed||flat)return;const dx=e.clientX-gesture.startX,dy=e.clientY-gesture.startY;if(!gesture.horizontal){if(Math.abs(dy)>8&&Math.abs(dy)>Math.abs(dx)){clearGesture();return;}if(Math.abs(dx)<7)return;gesture.horizontal=true;suppressClick=true;card.classList.add('dragging');card.setPointerCapture(e.pointerId);}if(e.cancelable)e.preventDefault();angle=base+Math.max(-MAX_TILT,Math.min(MAX_TILT,Math.sin(Math.max(-1,Math.min(1,dx/SWIPE_DISTANCE))*Math.PI/2)*MAX_TILT));render();if(Math.abs(dx)>=SWIPE_DISTANCE){gesture.consumed=true;flip(Math.sign(dx));}},{passive:false});
function release(e){if(!gesture||e.pointerId!==gesture.id)return;const consumed=gesture.consumed;clearGesture();if(!consumed&&!busy)animate(base,180);}
window.addEventListener('pointerup',release);window.addEventListener('pointercancel',release);window.addEventListener('blur',()=>{clearGesture();if(!busy){angle=base;render();}});
card.addEventListener('click',e=>{if(suppressClick&&e.detail!==0){e.preventDefault();e.stopPropagation();suppressClick=false;}},true);
card.addEventListener('keydown',e=>{if(e.target!==card)return;if(['ArrowLeft','ArrowRight','Enter',' ','Escape'].includes(e.key)){e.preventDefault();if(e.key==='Escape')reset();else flip(e.key==='ArrowLeft'?-1:1);}});
document.querySelector('#flip').onclick=()=>flip();document.querySelector('#reset').onclick=reset;
function setFlat(){stop();clearGesture();base=activeBack?180:0;angle=base;document.body.classList.toggle('flat',flat);document.querySelector('#motion').setAttribute('aria-pressed',String(flat));document.querySelector('#gesture-help').textContent=flat?'Modo sem efeitos · Use “Virar cartão” para ver o outro lado':'Deslize para um dos lados · Ao atingir o limite, o cartão vira sozinho';a11y(activeBack);render();}
document.querySelector('#motion').onclick=()=>{flat=!flat;setFlat();};reduced.addEventListener('change',e=>{flat=e.matches;setFlat();});setFlat();
let toastTimer;function notify(text){const el=document.querySelector('#status');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500)}
document.querySelector('#share').onclick=async()=>{const url='https://proxiti.com.br/cartao/';try{if(navigator.share){await navigator.share({title:'PROXITI · Um bom contato para ter por perto',text:'Suporte técnico sem tecniquês. Conheça a PROXITI.',url});return}}catch(e){if(e.name==='AbortError')return}try{await navigator.clipboard.writeText(url);notify('Link copiado. Pode enviar!')}catch{document.querySelector('#share-url').value=url;document.querySelector('#share-dialog').showModal();document.querySelector('#share-url').select()}};document.querySelector('#close-dialog').onclick=()=>document.querySelector('#share-dialog').close();
